services:
  dvgrab-web:
    build: .
    container_name: dvgrab-web
    devices:
      - /dev/fw0:/dev/fw0
      - /dev/fw1:/dev/fw1
    volumes:
      - /home/thorsten/media/minidv:/captures
    ports:
      - "5151:5000"
    privileged: true
    restart: unless-stopped
