name: dvgrab-webui

services:
  dvgrab-web:
    build: .
    devices:
      - /dev/fw0:/dev/fw0
      - /dev/fw1:/dev/fw1
    volumes:
      - ./captures:/captures
    ports:
      - "5151:5000"
    privileged: true
    restart: unless-stopped
